### ISSUE TITLE
Instalation guide

### ISSUE THREAD

**Issue by jurStv** [Defman21/komodo-emmet#1]
Hi, thx for this package!
but could you please guide me how to properly install this on komodo 9.3

**Comment by Defman21** [comment]
Open Commando with Packages scope, type `Emmet` and press Enter. Then restart Komodo.

**Comment by jurStv** [comment]
"This package is not compatible with your version of Komodo..." was shown to me after I pressed Enter. Is it ok?

**Comment by Defman21** [comment]
Yep.

**Comment by jurStv** [comment]
thanks then =)
